//! The desktop layer's mechanics (plans/done/v0.4-desktop-aerospace-borders.md):
//! write the generated `aerospace.toml` and ask AeroSpace to reload it, keep a
//! `borders` child alive with the flags the theme dictates, and set the hidden
//! window-corner-radius default. Every decision (what the toml says, which
//! colours, when to apply) is made in TypeScript — `@scuttlarr/core/desktop` —
//! and arrives here as bytes and argv. This module only compares, writes,
//! spawns and reloads. Idempotent on purpose: the frontend calls `apply` on
//! every config/theme change and at boot; nothing happens unless something
//! differs.

use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};

use crate::deps::{self, Dep, DepStatus};
use crate::error::{CmdError, CmdResult};

/// Our own file starts with this — `isManagedToml` in core is the same test.
const GENERATED_PREFIX: &str = "# generated by scuttlarr";
/// Files written before the 2026-09-11 rename carry this; still ours.
const LEGACY_GENERATED_PREFIX: &str = "# generated by launcharr";
const BACKUP_SUFFIX: &str = ".bak-scuttlarr";

/// Does this text carry our header (current or pre-rename)?
fn is_generated(text: &str) -> bool {
    text.starts_with(GENERATED_PREFIX) || text.starts_with(LEGACY_GENERATED_PREFIX)
}
/// Hidden AppKit global; verified on macOS 27.0 (2026-08-17). `0` reads as unset.
const CORNER_RADIUS_KEY: &str = "NSConvolutionOverride1";

pub fn aerospace_toml_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("/tmp"))
        .join(".config/aerospace/aerospace.toml")
}

/// What `~/.config/aerospace/aerospace.toml` currently is. Drives adopt-or-stop.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TomlState {
    Absent,
    /// Ours — safe to rewrite.
    Managed,
    /// Someone else's — never overwritten without `adopt`.
    Foreign,
}

pub fn toml_state() -> TomlState {
    match std::fs::read_to_string(aerospace_toml_path()) {
        Ok(text) if is_generated(&text) => TomlState::Managed,
        Ok(_) => TomlState::Foreign,
        Err(_) => TomlState::Absent,
    }
}

/// Everything the Settings → Desktop tab renders from. Mirrors `DesktopStatus` in TS.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopStatus {
    pub aerospace: DepStatus,
    pub borders: DepStatus,
    pub brew: bool,
    pub toml: TomlState,
    pub toml_path: String,
    pub borders_running: bool,
    /// Current `NSConvolutionOverride1`, if set (read back so the slider is truthful).
    pub corner_radius: Option<f64>,
    /// The native menu bar auto-hides (`_HIHideMenuBar = 1`). The AeroSpace top gap
    /// depends on it: a visible native bar already pushes windows down.
    pub menu_bar_hidden: bool,
}

pub fn status() -> DesktopStatus {
    DesktopStatus {
        aerospace: deps::status(Dep::Aerospace),
        borders: deps::status(Dep::Borders),
        brew: deps::brew().is_some(),
        toml: toml_state(),
        toml_path: aerospace_toml_path().to_string_lossy().into_owned(),
        borders_running: BORDERS.lock().map(|b| b.is_some()).unwrap_or(false),
        corner_radius: read_corner_radius(),
        menu_bar_hidden: read_menu_bar_hidden(),
    }
}

/// One `apply` request from the frontend. `toml: None` = don't touch the file
/// (tiling disabled or unmanaged); `borders: None` = borders should not run.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopApply {
    pub toml: Option<String>,
    pub borders_args: Option<Vec<String>>,
}

/// What `apply` did — the frontend surfaces `toml == Foreign` as the adopt prompt.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ApplyResult {
    pub toml: TomlState,
    pub toml_written: bool,
    pub aerospace_reloaded: bool,
    pub borders_running: bool,
}

pub fn apply(req: DesktopApply) -> CmdResult<ApplyResult> {
    let mut written = false;
    let mut reloaded = false;
    let state = toml_state();
    if let Some(toml) = req.toml {
        if !toml.starts_with(GENERATED_PREFIX) {
            return Err(CmdError::Internal(
                "refusing to write an aerospace.toml without the scuttlarr header".into(),
            ));
        }
        // A launcher-only install (zip, no AeroSpace) keeps ~/.config clean; the
        // file appears on the next apply after AeroSpace shows up.
        let installed = deps::locate(Dep::Aerospace.binary()).is_some();
        if state != TomlState::Foreign && installed {
            let path = aerospace_toml_path();
            let current = std::fs::read_to_string(&path).unwrap_or_default();
            if current != toml {
                write_atomic(&path, &toml)?;
                written = true;
            }
            if written {
                reloaded = reload_aerospace();
            }
        }
    }
    let borders_running = sync_borders(req.borders_args)?;
    Ok(ApplyResult {
        toml: if written { TomlState::Managed } else { state },
        toml_written: written,
        aerospace_reloaded: reloaded,
        borders_running,
    })
}

/// Take over a foreign toml: back it up beside itself, then the next `apply`
/// writes ours. Returns the backup path.
pub fn adopt() -> CmdResult<String> {
    let path = aerospace_toml_path();
    if toml_state() != TomlState::Foreign {
        return Err(CmdError::NotFound(
            "no foreign aerospace.toml to adopt".into(),
        ));
    }
    let backup = PathBuf::from(format!("{}{}", path.display(), BACKUP_SUFFIX));
    std::fs::rename(&path, &backup)?;
    Ok(backup.to_string_lossy().into_owned())
}

// ---- Unmanaged toml: your file, our symlink -----------------------------------
//
// With `managed` off scuttlarr never writes aerospace.toml, but it can still
// help you point AeroSpace at the file you actually keep (dotfiles) — a symlink
// at the canonical path — or hand you its generated config as a starting point.
// A later re-manage renames a fresh file over the symlink; your target is never
// written through.

/// Mirrors `TomlAction` in TS. The picker runs here (`osascript choose file`) so no
/// dialog plugin crate is needed; `None` = the user cancelled.
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum TomlAction {
    /// Pick an existing toml anywhere; symlink the canonical path to it.
    UseExisting,
    /// Pick where to save scuttlarr's current config; write it there (header
    /// rewritten so it no longer reads as managed) and symlink to it.
    SaveAs { toml: String },
}

pub fn toml_action(action: TomlAction) -> CmdResult<Option<String>> {
    let canonical = aerospace_toml_path();
    match action {
        TomlAction::UseExisting => {
            let Some(target) = pick_path(PickMode::Open)? else {
                return Ok(None);
            };
            link_canonical(&canonical, Path::new(&target))?;
            Ok(Some(target))
        }
        TomlAction::SaveAs { toml } => {
            let Some(target) = pick_path(PickMode::Save)? else {
                return Ok(None);
            };
            let target_path = PathBuf::from(&target);
            let text = exported_toml(&toml);
            if target_path == canonical {
                write_atomic(&canonical, &text)?;
            } else {
                write_atomic(&target_path, &text)?;
                link_canonical(&canonical, &target_path)?;
            }
            Ok(Some(target))
        }
    }
}

#[derive(Debug, Clone, Copy)]
enum PickMode {
    Open,
    Save,
}

/// AppleScript file dialogs — the settings window is an ordinary activating
/// window, so the sheet lands where the user is looking.
fn pick_path(mode: PickMode) -> CmdResult<Option<String>> {
    let script = match mode {
        PickMode::Open => r#"POSIX path of (choose file with prompt "Choose your aerospace.toml")"#,
        PickMode::Save => {
            r#"POSIX path of (choose file name with prompt "Save scuttlarr's AeroSpace config as" default name "aerospace.toml")"#
        }
    };
    let out = Command::new("/usr/bin/osascript")
        .args(["-e", script])
        .output()?;
    if !out.status.success() {
        // -128 = user cancelled; anything else is a real failure.
        let err = String::from_utf8_lossy(&out.stderr);
        return if err.contains("-128") {
            Ok(None)
        } else {
            Err(CmdError::Internal(format!("file dialog: {}", err.trim())))
        };
    }
    let path = String::from_utf8_lossy(&out.stdout).trim().to_owned();
    Ok((!path.is_empty()).then_some(path))
}

/// Replace whatever sits at the canonical path (file → `.bak-scuttlarr`, old
/// symlink → removed) with a symlink to `target`.
fn link_canonical(canonical: &Path, target: &Path) -> CmdResult<()> {
    if target == canonical {
        return Ok(());
    }
    if let Some(dir) = canonical.parent() {
        std::fs::create_dir_all(dir)?;
    }
    match std::fs::symlink_metadata(canonical) {
        Ok(meta) if meta.file_type().is_symlink() => std::fs::remove_file(canonical)?,
        Ok(_) => {
            let backup = PathBuf::from(format!("{}{}", canonical.display(), BACKUP_SUFFIX));
            std::fs::rename(canonical, &backup)?;
        }
        Err(_) => {}
    }
    std::os::unix::fs::symlink(target, canonical)?;
    Ok(())
}

/// The generated toml behind a "yours now" first line, so `toml_state()` reads
/// it as foreign from here on (the managed header is the first-line check).
fn exported_toml(toml: &str) -> String {
    format!("# exported from scuttlarr — yours to edit; scuttlarr won't touch it again\n{toml}")
}

fn write_atomic(path: &std::path::Path, contents: &str) -> std::io::Result<()> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    let tmp = path.with_extension("toml.scuttlarr-tmp");
    std::fs::write(&tmp, contents)?;
    std::fs::rename(&tmp, path)
}

/// `aerospace reload-config`; false when the CLI is missing or AeroSpace isn't
/// running (it reads the file at its own start, so that's fine).
fn reload_aerospace() -> bool {
    deps::locate(Dep::Aerospace.binary())
        .and_then(|bin| Command::new(bin).arg("reload-config").output().ok())
        .is_some_and(|o| o.status.success())
}

// ---- AeroSpace menu, as launcher rows ----------------------------------------
//
// `aerospace ⏎` mirrors the tray menu (workspaces, enable/disable, reload,
// open config, sponsor) so the menu bar item can go. Every action is a CLI call
// or an `open`; the workspace list is the bar's own query.

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AerospaceWorkspace {
    pub name: String,
    pub focused: bool,
    pub empty: bool,
}

pub fn workspaces() -> Vec<AerospaceWorkspace> {
    let Some(raw) = crate::bar::aerospace(&[
        "list-workspaces",
        "--all",
        "--format",
        "%{workspace}%{tab}%{workspace-is-focused}",
    ]) else {
        return Vec::new();
    };
    let empty: std::collections::HashSet<String> =
        crate::bar::aerospace(&["list-workspaces", "--monitor", "all", "--empty"])
            .map(|o| o.lines().map(|l| l.trim().to_owned()).collect())
            .unwrap_or_default();
    raw.lines()
        .filter_map(|l| {
            let mut it = l.split('\t');
            let name = it.next()?.trim();
            if name.is_empty() {
                return None;
            }
            let focused = it.next().map(str::trim) == Some("true");
            Some(AerospaceWorkspace {
                name: name.to_owned(),
                focused,
                empty: empty.contains(name),
            })
        })
        .collect()
}

/// Mirrors `AerospaceAction` in TS. Validated enum — never a raw argv across IPC.
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum AerospaceAction {
    Workspace {
        name: String,
    },
    /// `aerospace enable toggle` — pause/resume tiling.
    Toggle,
    ReloadConfig,
    /// scuttlarr's config when managed, else the toml itself.
    OpenConfig,
    Sponsor,
}

pub fn aerospace_action(action: AerospaceAction) -> CmdResult<()> {
    let ok = |r: Option<String>, what: &str| {
        r.map(|_| ())
            .ok_or_else(|| CmdError::Internal(format!("aerospace {what} failed")))
    };
    match action {
        AerospaceAction::Workspace { name } => crate::bar::switch_workspace(&name),
        AerospaceAction::Toggle => ok(
            crate::bar::aerospace(&["enable", "toggle"]),
            "enable toggle",
        ),
        AerospaceAction::ReloadConfig => {
            ok(crate::bar::aerospace(&["reload-config"]), "reload-config")
        }
        AerospaceAction::OpenConfig => {
            let path = match toml_state() {
                TomlState::Managed => crate::config::config_path(),
                _ => aerospace_toml_path(),
            };
            let status = Command::new("/usr/bin/open").arg("-t").arg(path).status()?;
            status
                .success()
                .then_some(())
                .ok_or_else(|| CmdError::Internal("open config failed".into()))
        }
        AerospaceAction::Sponsor => {
            let status = Command::new("/usr/bin/open")
                .arg("https://github.com/sponsors/nikitabobko")
                .status()?;
            status
                .success()
                .then_some(())
                .ok_or_else(|| CmdError::Internal("open sponsor page failed".into()))
        }
    }
}

// ---- JankyBorders supervision ------------------------------------------------
//
// One child, its argv remembered so re-applies with identical flags are no-ops
// and a theme change restarts it. No `bordersrc`: the flags are the config.
// Strays from a previous crash are cleared before we start ours; on orderly
// exit `shutdown` kills the child (RunEvent::Exit in lib.rs).

struct Borders {
    child: Child,
    args: Vec<String>,
}

static BORDERS: Mutex<Option<Borders>> = Mutex::new(None);

fn sync_borders(args: Option<Vec<String>>) -> CmdResult<bool> {
    let mut guard = BORDERS
        .lock()
        .map_err(|_| CmdError::Internal("borders lock poisoned".into()))?;
    // Reap a crashed child so it gets restarted below.
    if let Some(b) = guard.as_mut() {
        if b.child.try_wait().ok().flatten().is_some() {
            *guard = None;
        }
    }
    match args {
        None => {
            if let Some(mut b) = guard.take() {
                let _ = b.child.kill();
                let _ = b.child.wait();
            }
            Ok(false)
        }
        Some(args) => {
            if let Some(b) = guard.as_ref() {
                if b.args == args {
                    return Ok(true);
                }
            }
            let Some(bin) = deps::locate(Dep::Borders.binary()) else {
                return Ok(false);
            };
            if let Some(mut b) = guard.take() {
                let _ = b.child.kill();
                let _ = b.child.wait();
            } else {
                // A stray from a previous scuttlarr (crash) or a hand-started one.
                let _ = Command::new("/usr/bin/killall")
                    .arg("borders")
                    .stdout(Stdio::null())
                    .stderr(Stdio::null())
                    .status();
            }
            let child = Command::new(bin)
                .args(&args)
                .stdin(Stdio::null())
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .spawn()?;
            *guard = Some(Borders { child, args });
            Ok(true)
        }
    }
}

/// Orderly quit: take the border child with us.
pub fn shutdown() {
    if let Ok(mut guard) = BORDERS.lock() {
        if let Some(mut b) = guard.take() {
            let _ = b.child.kill();
            let _ = b.child.wait();
        }
    }
}

// ---- System corner radius ------------------------------------------------------

/// `defaults write -g NSConvolutionOverride1 -float N`, or `delete` for None.
/// Apps pick it up on relaunch; the frontend owns the clamp (1..=26) and the
/// wording, we only refuse nonsense.
pub fn set_corner_radius(radius: Option<f64>) -> CmdResult<()> {
    let mut cmd = Command::new("/usr/bin/defaults");
    match radius {
        Some(r) => {
            if !r.is_finite() || !(0.5..=64.0).contains(&r) {
                return Err(CmdError::Internal(format!(
                    "corner radius out of range: {r}"
                )));
            }
            cmd.args(["write", "-g", CORNER_RADIUS_KEY, "-float", &r.to_string()]);
        }
        None => {
            cmd.args(["delete", "-g", CORNER_RADIUS_KEY]);
        }
    }
    let out = cmd.output()?;
    // `defaults delete` on an unset key is a failure we don't care about.
    if out.status.success() || radius.is_none() {
        Ok(())
    } else {
        Err(CmdError::Internal(
            String::from_utf8_lossy(&out.stderr).trim().to_owned(),
        ))
    }
}

/// `defaults read -g _HIHideMenuBar` → 1 when the menu bar auto-hides. Absent = shown.
fn read_menu_bar_hidden() -> bool {
    Command::new("/usr/bin/defaults")
        .args(["read", "-g", "_HIHideMenuBar"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim() == "1")
        .unwrap_or(false)
}

fn read_corner_radius() -> Option<f64> {
    Command::new("/usr/bin/defaults")
        .args(["read", "-g", CORNER_RADIUS_KEY])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8_lossy(&o.stdout).trim().parse().ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pre_rename_header_still_reads_as_ours() {
        assert!(is_generated(
            "# generated by launcharr — edit config.json\n"
        ));
        assert!(is_generated(
            "# generated by scuttlarr — edit config.json\n"
        ));
        assert!(!is_generated("# mine\n"));
    }

    #[test]
    fn exported_toml_no_longer_reads_as_managed() {
        let out =
            exported_toml("# generated by scuttlarr — edit config.json\nconfig-version = 2\n");
        assert!(out.starts_with("# exported from scuttlarr"));
        assert!(out.ends_with("\nconfig-version = 2\n"));
        assert!(!is_generated(&out));
    }

    #[test]
    fn link_canonical_backs_up_files_and_replaces_links() {
        let dir = std::env::temp_dir().join(format!("scuttlarr-link-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let canonical = dir.join("aerospace.toml");
        let a = dir.join("a.toml");
        let b = dir.join("b.toml");
        std::fs::write(&canonical, "mine").unwrap();
        std::fs::write(&a, "a").unwrap();
        std::fs::write(&b, "b").unwrap();
        link_canonical(&canonical, &a).unwrap();
        assert_eq!(std::fs::read_to_string(&canonical).unwrap(), "a");
        assert_eq!(
            std::fs::read_to_string(dir.join("aerospace.toml.bak-scuttlarr")).unwrap(),
            "mine"
        );
        link_canonical(&canonical, &b).unwrap();
        assert_eq!(std::fs::read_to_string(&canonical).unwrap(), "b");
        assert!(std::fs::symlink_metadata(&canonical)
            .unwrap()
            .file_type()
            .is_symlink());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn apply_refuses_headerless_toml() {
        let err = apply(DesktopApply {
            toml: Some("config-version = 2\n".into()),
            borders_args: None,
        })
        .unwrap_err();
        assert!(matches!(err, CmdError::Internal(_)));
    }

    #[test]
    fn corner_radius_rejects_nonsense() {
        assert!(set_corner_radius(Some(0.0)).is_err());
        assert!(set_corner_radius(Some(f64::NAN)).is_err());
        assert!(set_corner_radius(Some(1000.0)).is_err());
    }
}
