/**
 * The desktop layer's product brain: the `desktop` config section (tiling via
 * AeroSpace, window borders via JankyBorders, the system corner radius) and the
 * pure renderers that turn it into what the tools consume — an `aerospace.toml`,
 * `borders` CLI flags, `defaults(1)` arguments. No I/O: Rust writes the file,
 * spawns the processes, and reloads (plans/done/v0.4-desktop-aerospace-borders.md,
 * DECISIONS 2026-08-17).
 *
 * The toml template is Mitch's daily config (dotfiles/macos/desktop/aerospace)
 * minus the personal/sketchybar bits. Everything not exposed as a knob is opinion,
 * on purpose; the escape hatch is `tiling.managed = false`, after which scuttlarr
 * never touches the file again.
 */

export type Modifier = 'alt' | 'ctrl' | 'cmd' | 'ctrl-alt' | 'alt-shift'
export const MODIFIERS: readonly Modifier[] = [
  'alt',
  'ctrl',
  'cmd',
  'ctrl-alt',
  'alt-shift',
]

export type BorderStyle = 'round' | 'square'

export interface TilingConfig {
  /** Tiling is part of this install at all (AeroSpace expected/supervised). */
  enabled: boolean
  /** scuttlarr owns ~/.config/aerospace/aerospace.toml. false = hand-edited, never written. */
  managed: boolean
  /** Prefix for every main-mode binding (`alt-h`, `ctrl-alt-h`, …). */
  modifier: Modifier
  /** Inner + outer gap in px. */
  gaps: number
  /** Persistent (always shown) workspaces 1..N, N ≤ 9; keys 1–9 always bind. */
  workspaces: number
  /** Bundle ids that always float. */
  float: string[]
}

export interface BordersConfig {
  enabled: boolean
  /** Border width in px (JankyBorders `width=`). */
  width: number
  style: BorderStyle
}

export interface DesktopConfig {
  tiling: TilingConfig
  borders: BordersConfig
  /** System window corner radius (`NSConvolutionOverride1`); null = leave macOS alone. */
  cornerRadius: number | null
}

export const DEFAULT_DESKTOP: DesktopConfig = {
  tiling: {
    enabled: true,
    managed: true,
    modifier: 'alt',
    gaps: 8,
    workspaces: 6,
    float: ['com.apple.systempreferences', 'com.raycast.macos'],
  },
  borders: { enabled: false, width: 5, style: 'round' },
  cornerRadius: null,
}

/** Mirrors the shape Rust persists verbatim; anything unknown collapses to defaults. */
export function normalizeDesktop(raw: unknown): DesktopConfig {
  const r = isRecord(raw) ? raw : {}
  const t = isRecord(r.tiling) ? r.tiling : {}
  const b = isRecord(r.borders) ? r.borders : {}
  const d = DEFAULT_DESKTOP
  return {
    tiling: {
      enabled: bool(t.enabled, d.tiling.enabled),
      managed: bool(t.managed, d.tiling.managed),
      modifier: MODIFIERS.includes(t.modifier as Modifier)
        ? (t.modifier as Modifier)
        : d.tiling.modifier,
      gaps: num(t.gaps, d.tiling.gaps),
      workspaces: num(t.workspaces, d.tiling.workspaces),
      float: Array.isArray(t.float)
        ? t.float.filter((x): x is string => typeof x === 'string')
        : d.tiling.float,
    },
    borders: {
      enabled: bool(b.enabled, d.borders.enabled),
      width: num(b.width, d.borders.width),
      style: b.style === 'square' ? 'square' : 'round',
    },
    cornerRadius:
      typeof r.cornerRadius === 'number' && Number.isFinite(r.cornerRadius)
        ? r.cornerRadius
        : null,
  }
}

// ---------------------------------------------------------------------------
// aerospace.toml

export const GENERATED_HEADER =
  '# generated by scuttlarr — edit ~/.config/scuttlarr/config.json (Settings → Desktop),\n' +
  '# or set desktop.tiling.managed = false to take this file over by hand.'

/** Our own file? Decides adopt-or-stop on first launch and whether a rewrite is safe. */
export function isManagedToml(text: string): boolean {
  return text.startsWith('# generated by scuttlarr')
}

export const MAX_WORKSPACES = 9

export interface RenderOptions {
  /** Height of scuttlarr's bar strip in points; 0 = bar off. */
  barHeight?: number
  /** The native menu bar auto-hides (`_HIHideMenuBar = 1`). When it is *visible*
   * AeroSpace already measures the top gap from below it. */
  menuBarHidden?: boolean
}

/** Height of the native macOS menu bar on external displays (points). */
export const NATIVE_MENU_BAR_HEIGHT = 24

export interface GapPlan {
  inner: number
  outer: number
  outerTopBuiltIn: number
  outerTopExternal: number
}

/**
 * `gaps` means the gap you *see* (Mitch, 2026-08-17). JankyBorders draws its border
 * centred on the window frame, so half of `width` lands in every gap: between two
 * windows that is a whole width, at a screen edge half of one. Top: AeroSpace lays
 * out inside `visibleFrame`, which already excludes a *visible* native menu bar and
 * the notch band of built-in displays; a hidden native bar means externals start
 * at y=0, so scuttlarr's strip (when on) is added — and if both are showing, only
 * the part of the strip that pokes below the native bar.
 */
export function gapPlan(
  desktop: DesktopConfig,
  opts: RenderOptions = {},
): GapPlan {
  const gaps = clampInt(desktop.tiling.gaps, 0, 64)
  const border = desktop.borders.enabled
    ? clamp(desktop.borders.width, BORDER_WIDTH_MIN, BORDER_WIDTH_MAX)
    : 0
  const inner = gaps + Math.ceil(border)
  const outer = gaps + Math.ceil(border / 2)
  const barHeight = clampInt(opts.barHeight ?? 0, 0, 200)
  const menuBarHidden = opts.menuBarHidden ?? true
  const topReserve = menuBarHidden
    ? barHeight
    : Math.max(0, barHeight - NATIVE_MENU_BAR_HEIGHT)
  return {
    inner,
    outer,
    outerTopBuiltIn: outer,
    outerTopExternal: outer + topReserve,
  }
}

export function renderAerospaceToml(
  desktop: DesktopConfig,
  opts: RenderOptions = {},
): string {
  const t = desktop.tiling
  const mod = t.modifier
  const gap = gapPlan(desktop, opts)
  const n = clampInt(t.workspaces, 1, MAX_WORKSPACES)
  const ws = Array.from({ length: n }, (_, i) => String(i + 1))
  // Keys 1–9 always work (AeroSpace creates a workspace on demand); N only
  // decides which ones persist in the bar when empty.
  const keys = Array.from({ length: MAX_WORKSPACES }, (_, i) => String(i + 1))
  const floats = t.float
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && /^[A-Za-z0-9._-]+$/.test(s))

  const lines: string[] = [
    GENERATED_HEADER,
    '',
    'config-version = 2',
    'start-at-login = true',
    '',
    "# scuttlarr's bar re-snapshots when anything in its triggers/ dir changes.",
    "exec-on-workspace-change = ['/bin/bash', '-c',",
    '  \'touch "$HOME/.config/scuttlarr/triggers/workspace"\'',
    ']',
    '',
    'enable-normalization-flatten-containers = true',
    'enable-normalization-opposite-orientation-for-nested-containers = true',
    'accordion-padding = 28',
    "default-root-container-layout = 'tiles'",
    "default-root-container-orientation = 'auto'",
    "on-focused-monitor-changed = ['move-mouse monitor-lazy-center']",
    'automatically-unhide-macos-hidden-apps = false',
    '',
    `persistent-workspaces = [${ws.map((w) => `'${w}'`).join(', ')}]`,
    '',
    '[exec]',
    'inherit-env-vars = true',
    '',
    '[exec.env-vars]',
    "PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:${PATH}'",
    '',
    '[gaps]',
    `# visible gap ${clampInt(t.gaps, 0, 64)}px; borders and the bar are already factored in.`,
    `inner.horizontal = ${gap.inner}`,
    `inner.vertical = ${gap.inner}`,
    `outer.left = ${gap.outer}`,
    `outer.bottom = ${gap.outer}`,
    '# Built-in displays reserve notch/menu-bar space already; externals add room for the bar.',
    `outer.top = [{ monitor."built-in.*" = ${gap.outerTopBuiltIn} }, ${gap.outerTopExternal}]`,
    `outer.right = ${gap.outer}`,
    '',
    '[mode.main.binding]',
    `${mod}-slash = 'layout tiles horizontal vertical'`,
    `${mod}-comma = 'layout accordion horizontal vertical'`,
    `${mod}-f = 'fullscreen'`,
    `${mod}-shift-space = 'layout floating tiling'`,
    '',
    `${mod}-h = 'focus left'`,
    `${mod}-j = 'focus down'`,
    `${mod}-k = 'focus up'`,
    `${mod}-l = 'focus right'`,
    '',
    "ctrl-left = 'workspace --wrap-around prev'",
    "ctrl-right = 'workspace --wrap-around next'",
    '',
    `${mod}-shift-h = 'move left'`,
    `${mod}-shift-j = 'move down'`,
    `${mod}-shift-k = 'move up'`,
    `${mod}-shift-l = 'move right'`,
    '',
    `${mod}-minus = 'resize smart -50'`,
    `${mod}-equal = 'resize smart +50'`,
    '',
    ...keys.map((w) => `${mod}-${w} = 'workspace ${w}'`),
    '',
    ...keys.map(
      (w) =>
        `${mod}-shift-${w} = ['move-node-to-workspace ${w}', 'workspace ${w}']`,
    ),
    '',
    `${mod}-tab = 'workspace-back-and-forth'`,
    `${mod}-shift-tab = 'move-workspace-to-monitor --wrap-around next'`,
    '',
    `${mod}-r = 'mode resize'`,
    `${mod}-semicolon = 'mode service'`,
    '',
    '[mode.resize.binding]',
    "h = 'resize width -50'",
    "j = 'resize height +50'",
    "k = 'resize height -50'",
    "l = 'resize width +50'",
    "minus = 'resize smart -50'",
    "equal = 'resize smart +50'",
    "esc = 'mode main'",
    "enter = 'mode main'",
    '',
    '[mode.service.binding]',
    "r = ['reload-config', 'mode main']",
    "f = ['flatten-workspace-tree', 'mode main']",
    "backspace = ['close-all-windows-but-current', 'mode main']",
    "esc = 'mode main'",
    "enter = 'mode main'",
    '',
    '[[on-window-detected]]',
    "if.app-id = 'com.apple.finder'",
    "if.window-title-regex-substring = 'Copy|Move|Info|Preferences'",
    "run = 'layout floating'",
  ]
  for (const id of floats) {
    lines.push(
      '',
      '[[on-window-detected]]',
      `if.app-id = '${id}'`,
      "run = 'layout floating'",
    )
  }
  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// JankyBorders

export interface BorderColors {
  /** Focused-window border. */
  accent: string
  /** Theme border line — the dark end of the unfocused ring's tone. */
  border: string
  /** Theme text — the light end of the unfocused ring's tone. */
  fg: string
  /** Faint fill behind the border. */
  bg: string
}

/**
 * Unfocused ring: a *solid* tone 57% of the way from `border` to `fg`. Settled by
 * eye on 2026-08-17 (DECISIONS): translucent dim rings read as gap (an 8px gap
 * looked 10), surface/border tones vanished into a dark wallpaper, translucent fg
 * washed out — a solid mid tone is what reads as "window edge" so the visible gap
 * matches the real one. For scuttlarr's theme this lands on #8083a0.
 */
export const INACTIVE_MIX = 0.57

export function inactiveBorderColor(
  colors: Pick<BorderColors, 'border' | 'fg'>,
): string {
  const a = parseCss(colors.border.trim()) ?? { r: 57, g: 59, b: 84, a: 1 }
  const b = parseCss(colors.fg.trim()) ?? { r: 181, g: 185, b: 217, a: 1 }
  const mix = (x: number, y: number) => Math.round(x + (y - x) * INACTIVE_MIX)
  const hex = (n: number) => clamp(n, 0, 255).toString(16).padStart(2, '0')
  return `#${hex(mix(a.r, b.r))}${hex(mix(a.g, b.g))}${hex(mix(a.b, b.b))}`
}

const BACKGROUND_ALPHA = 48 / 255
export const BORDER_WIDTH_MIN = 1
export const BORDER_WIDTH_MAX = 20

/** Arguments for `borders …` (no config file: flags are the config, rendered from the theme). */
export function bordersArgs(
  desktop: DesktopConfig,
  colors: BorderColors,
): string[] {
  const width = clamp(
    Number.isFinite(desktop.borders.width) ? desktop.borders.width : 5,
    BORDER_WIDTH_MIN,
    BORDER_WIDTH_MAX,
  )
  return [
    `active_color=${cssToBordersColor(colors.accent)}`,
    `inactive_color=${cssToBordersColor(inactiveBorderColor(colors))}`,
    `background_color=${cssToBordersColor(colors.bg, BACKGROUND_ALPHA)}`,
    `width=${trimNumber(width)}`,
    'hidpi=on',
    `style=${desktop.borders.style === 'square' ? 'square' : 'round'}`,
  ]
}

/** CSS colour (#rgb, #rrggbb, #rrggbbaa, rgb()/rgba()) → JankyBorders `0xAARRGGBB`. */
export function cssToBordersColor(css: string, alphaOverride?: number): string {
  const parsed = parseCss(css.trim()) ?? { r: 255, g: 255, b: 255, a: 1 }
  const a = alphaOverride ?? parsed.a
  const hex = (n: number) =>
    Math.round(clamp(n, 0, 255))
      .toString(16)
      .padStart(2, '0')
  return `0x${hex(a * 255)}${hex(parsed.r)}${hex(parsed.g)}${hex(parsed.b)}`
}

function parseCss(
  s: string,
): { r: number; g: number; b: number; a: number } | null {
  const hexMatch = /^#([0-9a-f]{3,8})$/i.exec(s)
  if (hexMatch) {
    let h = hexMatch[1] ?? ''
    if (h.length === 3 || h.length === 4)
      h = h
        .split('')
        .map((c) => c + c)
        .join('')
    if (h.length !== 6 && h.length !== 8) return null
    const n = (i: number) => parseInt(h.slice(i, i + 2), 16)
    return { r: n(0), g: n(2), b: n(4), a: h.length === 8 ? n(6) / 255 : 1 }
  }
  const fn =
    /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i.exec(
      s,
    )
  if (fn) {
    const [, r, g, b, a] = fn
    return {
      r: Number(r),
      g: Number(g),
      b: Number(b),
      a: a === undefined ? 1 : Number(a),
    }
  }
  return null
}

// ---------------------------------------------------------------------------
// System corner radius (hidden AppKit global; verified 2026-08-17 on macOS 27.0)

export const CORNER_RADIUS_KEY = 'NSConvolutionOverride1'
/** 0 is read as "unset" by AppKit — the smallest effective value is 1. */
export const CORNER_RADIUS_MIN = 1
/** Tahoe's default; larger only makes things rounder than stock. */
export const CORNER_RADIUS_MAX = 26

export function clampCornerRadius(n: number): number {
  if (!Number.isFinite(n)) return CORNER_RADIUS_MAX
  return clampInt(n, CORNER_RADIUS_MIN, CORNER_RADIUS_MAX)
}

/** Arguments for `defaults …` — write for a radius, delete to hand control back to macOS. */
export function cornerRadiusArgs(radius: number | null): string[] {
  if (radius === null) return ['delete', '-g', CORNER_RADIUS_KEY]
  return [
    'write',
    '-g',
    CORNER_RADIUS_KEY,
    '-float',
    String(clampCornerRadius(radius)),
  ]
}

// ---------------------------------------------------------------------------

function isRecord(x: unknown): x is Record<string, unknown> {
  return typeof x === 'object' && x !== null && !Array.isArray(x)
}
function bool(x: unknown, d: boolean): boolean {
  return typeof x === 'boolean' ? x : d
}
function num(x: unknown, d: number): number {
  return typeof x === 'number' && Number.isFinite(x) ? x : d
}
function clamp(n: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, n))
}
function clampInt(n: number, lo: number, hi: number): number {
  return Math.round(clamp(Number.isFinite(n) ? n : lo, lo, hi))
}
function trimNumber(n: number): string {
  return Number.isInteger(n) ? String(n) : String(Math.round(n * 100) / 100)
}
