{
  "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
  "name": "scuttlarr",
  "author": "scuttlarr — rendered from theme {{ name }}, do not edit",
  "themes": [
    {
      "name": "scuttlarr",
      "appearance": "{{ mode }}",
      "style": {
        "background": "{{ background }}",
        "background.appearance": "opaque",
        "border": "{{ selection }}",
        "border.variant": "{{ lighter_background }}",
        "border.focused": "{{ accent }}",
        "border.selected": "{{ accent }}",
        "border.transparent": "#00000000",
        "border.disabled": "{{ muted }}",
        "elevated_surface.background": "{{ lighter_background }}",
        "surface.background": "{{ dark_background }}",
        "element.background": "{{ lighter_background }}",
        "element.hover": "{{ selection }}",
        "element.active": "{{ selection }}",
        "element.selected": "{{ selection }}",
        "element.disabled": "{{ dark_background }}",
        "drop_target.background": "{{ mix accent background 30% }}",
        "ghost_element.background": "#00000000",
        "ghost_element.hover": "{{ lighter_background }}",
        "ghost_element.active": "{{ selection }}",
        "ghost_element.selected": "{{ selection }}",
        "ghost_element.disabled": "{{ dark_background }}",
        "text": "{{ foreground }}",
        "text.muted": "{{ dark_foreground }}",
        "text.placeholder": "{{ muted }}",
        "text.disabled": "{{ muted }}",
        "text.accent": "{{ accent }}",
        "icon": "{{ foreground }}",
        "icon.muted": "{{ dark_foreground }}",
        "icon.disabled": "{{ muted }}",
        "icon.placeholder": "{{ muted }}",
        "icon.accent": "{{ accent }}",
        "status_bar.background": "{{ dark_background }}",
        "title_bar.background": "{{ dark_background }}",
        "title_bar.inactive_background": "{{ darker_background }}",
        "toolbar.background": "{{ background }}",
        "tab_bar.background": "{{ dark_background }}",
        "tab.inactive_background": "{{ dark_background }}",
        "tab.active_background": "{{ background }}",
        "search.match_background": "{{ mix yellow background 35% }}",
        "panel.background": "{{ dark_background }}",
        "panel.focused_border": "{{ accent }}",
        "panel.indent_guide": "{{ lighter_background }}",
        "panel.indent_guide_hover": "{{ selection }}",
        "panel.indent_guide_active": "{{ muted }}",
        "pane.focused_border": "{{ accent }}",
        "pane_group.border": "{{ selection }}",
        "scrollbar.thumb.background": "{{ mix foreground background 25% }}",
        "scrollbar.thumb.hover_background": "{{ mix foreground background 40% }}",
        "scrollbar.thumb.border": "{{ selection }}",
        "scrollbar.track.background": "#00000000",
        "scrollbar.track.border": "{{ lighter_background }}",
        "editor.foreground": "{{ foreground }}",
        "editor.background": "{{ background }}",
        "editor.gutter.background": "{{ background }}",
        "editor.subheader.background": "{{ lighter_background }}",
        "editor.active_line.background": "{{ lighter_background }}",
        "editor.highlighted_line.background": "{{ mix accent background 15% }}",
        "editor.line_number": "{{ muted }}",
        "editor.active_line_number": "{{ foreground }}",
        "editor.invisible": "{{ muted }}",
        "editor.wrap_guide": "{{ lighter_background }}",
        "editor.active_wrap_guide": "{{ selection }}",
        "editor.indent_guide": "{{ lighter_background }}",
        "editor.indent_guide_active": "{{ selection }}",
        "editor.document_highlight.read_background": "{{ mix accent background 20% }}",
        "editor.document_highlight.write_background": "{{ mix accent background 30% }}",
        "editor.document_highlight.bracket_background": "{{ mix accent background 20% }}",
        "terminal.background": "{{ background }}",
        "terminal.foreground": "{{ foreground }}",
        "terminal.bright_foreground": "{{ bright_foreground }}",
        "terminal.dim_foreground": "{{ dark_foreground }}",
        "terminal.ansi.background": "{{ background }}",
        "terminal.ansi.foreground": "{{ foreground }}",
        "terminal.ansi.black": "{{ background }}",
        "terminal.ansi.bright_black": "{{ muted }}",
        "terminal.ansi.dim_black": "{{ darker_background }}",
        "terminal.ansi.red": "{{ red }}",
        "terminal.ansi.bright_red": "{{ bright_red }}",
        "terminal.ansi.dim_red": "{{ mix red background 50% }}",
        "terminal.ansi.green": "{{ green }}",
        "terminal.ansi.bright_green": "{{ bright_green }}",
        "terminal.ansi.dim_green": "{{ mix green background 50% }}",
        "terminal.ansi.yellow": "{{ yellow }}",
        "terminal.ansi.bright_yellow": "{{ bright_yellow }}",
        "terminal.ansi.dim_yellow": "{{ mix yellow background 50% }}",
        "terminal.ansi.blue": "{{ blue }}",
        "terminal.ansi.bright_blue": "{{ bright_blue }}",
        "terminal.ansi.dim_blue": "{{ mix blue background 50% }}",
        "terminal.ansi.magenta": "{{ magenta }}",
        "terminal.ansi.bright_magenta": "{{ bright_magenta }}",
        "terminal.ansi.dim_magenta": "{{ mix magenta background 50% }}",
        "terminal.ansi.cyan": "{{ cyan }}",
        "terminal.ansi.bright_cyan": "{{ bright_cyan }}",
        "terminal.ansi.dim_cyan": "{{ mix cyan background 50% }}",
        "terminal.ansi.white": "{{ foreground }}",
        "terminal.ansi.bright_white": "{{ bright_foreground }}",
        "terminal.ansi.dim_white": "{{ dark_foreground }}",
        "link_text.hover": "{{ accent }}",
        "conflict": "{{ orange }}",
        "conflict.background": "{{ mix orange background 20% }}",
        "conflict.border": "{{ orange }}",
        "created": "{{ green }}",
        "created.background": "{{ mix green background 20% }}",
        "created.border": "{{ green }}",
        "deleted": "{{ red }}",
        "deleted.background": "{{ mix red background 20% }}",
        "deleted.border": "{{ red }}",
        "error": "{{ red }}",
        "error.background": "{{ mix red background 20% }}",
        "error.border": "{{ red }}",
        "hidden": "{{ muted }}",
        "hidden.background": "{{ dark_background }}",
        "hidden.border": "{{ muted }}",
        "hint": "{{ cyan }}",
        "hint.background": "{{ mix cyan background 20% }}",
        "hint.border": "{{ cyan }}",
        "ignored": "{{ muted }}",
        "ignored.background": "{{ dark_background }}",
        "ignored.border": "{{ muted }}",
        "info": "{{ blue }}",
        "info.background": "{{ mix blue background 20% }}",
        "info.border": "{{ blue }}",
        "modified": "{{ yellow }}",
        "modified.background": "{{ mix yellow background 20% }}",
        "modified.border": "{{ yellow }}",
        "predictive": "{{ muted }}",
        "predictive.background": "{{ dark_background }}",
        "predictive.border": "{{ muted }}",
        "renamed": "{{ cyan }}",
        "renamed.background": "{{ mix cyan background 20% }}",
        "renamed.border": "{{ cyan }}",
        "success": "{{ green }}",
        "success.background": "{{ mix green background 20% }}",
        "success.border": "{{ green }}",
        "unreachable": "{{ muted }}",
        "unreachable.background": "{{ dark_background }}",
        "unreachable.border": "{{ muted }}",
        "warning": "{{ yellow }}",
        "warning.background": "{{ mix yellow background 20% }}",
        "warning.border": "{{ yellow }}",
        "players": [
          { "cursor": "{{ bright_foreground }}", "background": "{{ accent }}", "selection": "{{ selection_background }}" },
          { "cursor": "{{ green }}", "background": "{{ green }}", "selection": "{{ mix green background 30% }}" },
          { "cursor": "{{ magenta }}", "background": "{{ magenta }}", "selection": "{{ mix magenta background 30% }}" },
          { "cursor": "{{ yellow }}", "background": "{{ yellow }}", "selection": "{{ mix yellow background 30% }}" },
          { "cursor": "{{ cyan }}", "background": "{{ cyan }}", "selection": "{{ mix cyan background 30% }}" },
          { "cursor": "{{ red }}", "background": "{{ red }}", "selection": "{{ mix red background 30% }}" },
          { "cursor": "{{ blue }}", "background": "{{ blue }}", "selection": "{{ mix blue background 30% }}" },
          { "cursor": "{{ orange }}", "background": "{{ orange }}", "selection": "{{ mix orange background 30% }}" }
        ],
        "syntax": {
          "attribute": { "color": "{{ yellow }}" },
          "boolean": { "color": "{{ orange }}" },
          "comment": { "color": "{{ muted }}", "font_style": "italic" },
          "comment.doc": { "color": "{{ muted }}", "font_style": "italic" },
          "constant": { "color": "{{ orange }}" },
          "constructor": { "color": "{{ blue }}" },
          "embedded": { "color": "{{ foreground }}" },
          "emphasis": { "font_style": "italic" },
          "emphasis.strong": { "font_weight": 700 },
          "enum": { "color": "{{ yellow }}" },
          "function": { "color": "{{ blue }}" },
          "function.method": { "color": "{{ blue }}" },
          "hint": { "color": "{{ cyan }}", "font_weight": 700 },
          "keyword": { "color": "{{ magenta }}" },
          "label": { "color": "{{ blue }}" },
          "link_text": { "color": "{{ blue }}", "font_style": "italic" },
          "link_uri": { "color": "{{ cyan }}" },
          "number": { "color": "{{ orange }}" },
          "operator": { "color": "{{ cyan }}" },
          "predictive": { "color": "{{ muted }}", "font_style": "italic" },
          "preproc": { "color": "{{ magenta }}" },
          "primary": { "color": "{{ foreground }}" },
          "property": { "color": "{{ cyan }}" },
          "punctuation": { "color": "{{ dark_foreground }}" },
          "punctuation.bracket": { "color": "{{ dark_foreground }}" },
          "punctuation.delimiter": { "color": "{{ dark_foreground }}" },
          "punctuation.list_marker": { "color": "{{ cyan }}" },
          "punctuation.special": { "color": "{{ magenta }}" },
          "string": { "color": "{{ green }}" },
          "string.escape": { "color": "{{ magenta }}" },
          "string.regex": { "color": "{{ bright_cyan }}" },
          "string.special": { "color": "{{ green }}" },
          "string.special.symbol": { "color": "{{ orange }}" },
          "tag": { "color": "{{ blue }}" },
          "text.literal": { "color": "{{ green }}" },
          "title": { "color": "{{ foreground }}", "font_weight": 700 },
          "type": { "color": "{{ yellow }}" },
          "variable": { "color": "{{ foreground }}" },
          "variable.special": { "color": "{{ red }}" },
          "variant": { "color": "{{ yellow }}" }
        }
      }
    }
  ]
}
